import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "blue",
  },
  input: {
    height: 48,
    borderRadius: 5,
    overflow: "hidden",
    backgroundColor: "white",
    marginTop: 10,
    marginBottom: 10,
    marginLeft: 30,
    marginRight: 30,
    paddingLeft: 16,
  },
  container: {
    flex: 1,
    backgroundColor: "#484240",
    color: "white",
  },
  content: {
    flex: 1,
    color: "#EA9547",
    backgroundColor: "#484240",
    bottomPadding: 0,
  },
  footer: {
    backgroundColor: "#484240",
    padding: 20,
  },
  button: {
    color: "white",
  },
  menuButtons: {
    height: 50,
    marginHorizontal: 10,
    backgroundColor: "#EA9547",
    borderRadius: "30",
    alignItems: "center",
    margin: "10%",
    justifyContent: "center",
  },
  buttonText: {
    fontSize: 20,
    padding: 0,
    color: "#2B937E",
  },
  Icon: {
    height: 100,
    width: 100,
    paddingRight: 120,
    paddingLeft: 120,
    // paddingVertical: 30,
    paddingBottom: 50,
    marginLeft: 70,
    marginTop: 25,
  },
  Icontwo: {
    height: 150,
    width: 100,
    paddingRight: 120,
    paddingLeft: 120,
    // paddingVertical: 30,
    paddingBottom: 0,
    marginLeft: 70,
    marginTop: 25,
    marginBottom: 0,
  },
  textstyleone: {
    color: "white",
  },
  plantContainer: {
    flex: 1,
    alignItems: "center",
    marginBottom: 0,
    marginHorizontal: 40,
    marginTop: 0,
    padding: 0,
    backgroundColor: "#D6D7DB",
    borderRadius: 50,
    shadowColor: "#000000",
    shadowOpacity: 0.2,
    shadowOffset: {
      width: 1,
      height: 1,
    },
    elevation: 2,
  },
  mpscroll: {
    borderRadius: 50,
    backgroundColor: "red",
    margin: 0,
  },
  plantImage: {
    width: "30%",
    height: 50,
    marginBottom: 10,
    marginTop: 10,
    borderRadius: 50,
  },
  pager: {
    flex: 1,
    backgroundColor: "#484240",
    alignSelf: "stretch",
    padding: 100,
    height: 70,
    marginTop: 0,
  },
  plantcard: {
    backgroundColor: "#484240",
    marginBottom: 50,
    marginHorizontal: 30,
  },
  title: {
    fontWeight: "bold",
  },
  arrows: {
    height: 80,
    width: "100%",
    paddingRight: 10,
    paddingLeft: 10,
    // paddingVertical: 30,
    paddingBottom: 0,

    marginTop: -140,
  },
});
