import { StyleSheet } from "react-native";
import Constants from "expo-constants";

export default StyleSheet.create({
  spacer: {
    padding: 10,
    color: "#EA9547",
  },
  container: {
    flex: 1,
    backgroundColor: "#484240",
    paddingTop: "17%",
  },
  bubble: {
    flexDirection: "column",
    alignSelf: "flex-start",
    backgroundColor: "#fff",
    borderRadius: 6,
    borderColor: "#ccc",
    borderWidth: 0.5,
    padding: 15,
    width: 150,
  },
  name: {
    fontSize: 16,
    marginBottom: 5,
  },
  input: {
    height: 80,
    borderRadius: 5,
    overflow: "hidden",
    backgroundColor: "white",
    marginTop: 10,
    marginBottom: 10,
    marginLeft: 30,
    marginRight: 30,
    paddingLeft: 16,
  },
  arrow: {
    backgroundColor: "transparent",
    borderColor: "transparent",
    borderTopColor: "#fff",
    borderWidth: 16,
    alignSelf: "center",
    marginTop: -32,
  },
  arrowBorder: {
    backgroundColor: "transparent",
    borderColor: "transparent",
    borderTopColor: "#007a87",
    borderWidth: 16,
    alignSelf: "center",
    marginTop: -0.5,
  },
  body: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 10,
  },
  map: {
    width: "90%",
    height: "60%",
    borderColor: "#3A914F",
    paddingVertical: 30,
    marginBottom: 50,
    borderRadius: 30,
  },
  footer: {
    paddingBottom: Constants.statusBarHeight,
    bottom: "-3%",
    backgroundColor: "#484240",
    paddingTop: 10,
    paddingHorizontal: 25,
  },
  header: {
    fontSize: 20,
    fontWeight: "700",
  },
  searchContainer: {
    position: "absolute",
    height: "5%",
    width: "65%",
    backgroundColor: "white",
    shadowColor: "black",
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 4,
    elevation: 4,
    padding: 8,
    borderRadius: 8,
  },
  input: {
    borderColor: "#888",
    borderWidth: 1,
  },
  Icon: {
    height: 100,
    width: 200,
    paddingRight: 150,
    paddingLeft: 150,
    // paddingVertical: 30,
    // paddingBottom: 50,
    marginLeft: 25,
    // marginTop: 25,
  },
  drop: {
    borderRadius: 20,
    backgroundColor: "#EA9547",
  },
  infoText: {
    color: "#EA9547",
  },
});
